### ISSUE TITLE
Build failing, asserts not successful

### ISSUE THREAD

**Issue by jazzdup** [binxio/slackbot-on-google-cloud-platform-template#1]
Hi, cloudbuild fails due to code issue.
Removing the asserts, it builds OK. 
I ran copier locally with python 3.11 but the build uses 3.9, I presume that's the reason? Will try again at some point.
[dali_log.txt](https://github.com/binxio/slackbot-on-google-cloud-platform-template/files/11359167/dali_log.txt)

**Comment by jazzdup** [comment]
Same error using 3.9 and turns out it's basic code issue, I needed to change test to:
`def ack(*args, **kwargs):
    global ack_called
    ack_called = True`
Also needs 2 more api's enabled to deploy:
cloudresourcemanager.googleapis.com
iam.googleapis.com
If you just want a PR, let me know. Thanks for this demo, it's cool!

**Comment by mvanholsteijn** [comment]
Good to hear you are happy. A PR would be welcome.
